### ISSUE TITLE
This contest is big fail!

### ISSUE THREAD

**Issue by zbitname** [hola/challenge_mail_filter#2]
Programmer who created this benchmark have no conscience and enough competence or just lazy man.

**Comment by xderry** [comment]
Thanks for your feedback. We are re-checking the results, and will update soon.

http://hola.org/dna#truth-mistakes

**Comment by catamphetamine** [comment]
+1 to the OP

**Comment by feldgendler** [comment]
We have addressed the criticism in the new version of README.md.

**Comment by catamphetamine** [comment]
:thumbsup:
Thumbs up for admitting your mistakes (and correcting the benchmark procedure and reviewing the winners).

That's always better than denying them.
http://habrahabr.ru/company/hola/blog/274697/#comment_8730883

Antelle

> Тормозит доступ к global (как, соответственно, и вызов любой функции из глобального пространства). 
> local: 88.315ms
> vm: 12191.585ms
> Если у Roman Pletnev check засунуть внутрь filter, его код быстрее.

@zbitname 

> Думаю, что это серьёзный повод пересмотреть результаты. 

@feldgendler 

> Как и в прошлом конкурсе, мы сделаем выводы на следующий раз, но пересматривать результаты не будем.

I personally have no interest in reviewing the winners because my solution is still slower and not that advanced but me too was amused at first when the initial results were published announcing my function execution time about 13 seconds as opposed to 0.5 sec when run "as usual" on the same data set (on my machine) which is a 30 times difference.
